### ISSUE TITLE
CaseClauseError in lib/exirc/utils.ex:35 causes crash

### ISSUE THREAD

**Issue by Annwenn** [bitwalker/exirc#36]
Here's the trace: 
```
15:01:15.697 [error] GenServer terminating
** (CaseClauseError) no case clause matching: ["Uniaika", "!", "", ".", "", "@", "localhost"]
    (exirc) lib/exirc/utils.ex:35: ExIrc.Utils.parse_from/2
    (exirc) lib/exirc/utils.ex:22: ExIrc.Utils.parse/1
    (exirc) lib/exirc/client.ex:480: ExIrc.Client.handle_info/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:tcp, #Port<0.7776>, ':Uniaika!.@localhost PRIVMSG #Paris :!\r\n'}
```

I don't know if it's related to the fact that my username is simple `.`, in which case I can definitely change it.

**Comment by bitwalker** [comment]
Found the issue and pushed a new release :)

**Comment by Annwenn** [comment]
Thanks :)
